#!/usr/bin/env python3
"""Opening hours for both offices, stated once.

Hours appeared in eleven places across eight files, and they had already drifted
apart in the way that costs something: the Palm Beach Gardens JSON-LD asserted
Mon-Thu 8-5 / Fri 8-2, copied wholesale from Jupiter, for an office that opens
Monday and Wednesday only -- while the visible copy on the same site said "call
for current days and availability". Structured data and page copy contradicting
each other is bad; both being wrong about a locked door on a Tuesday is worse.

So the schedules live here and everything else renders from them. build.py
exposes the renderers as {{HOURS_*}} tokens, substituted after {{CONTENT}} so
they reach page bodies and page-level schema, not just the shared template.

Two consumers cannot be reached this way -- assets/js/assistant.js and llms.txt
are hand-maintained and not generated by build.py. _dev/preflight.py imports
plain() and asserts their text still matches, so the drift fails a gate instead
of quietly shipping.
"""

# Day order matters for rendering: schema.org accepts any order, humans do not.
_ORDER = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday",
          "Saturday", "Sunday"]

_ABBR = {"Monday": "Mon", "Tuesday": "Tue", "Wednesday": "Wed",
         "Thursday": "Thu", "Friday": "Fri", "Saturday": "Sat",
         "Sunday": "Sun"}


class Office:
    """One office's schedule.

    `days` maps a day name to an (opens, closes) pair in 24-hour "HH:MM".
    A day absent from the mapping is closed, and closed days are never emitted
    as an OpeningHoursSpecification -- schema.org has no "closed" entry, and
    inventing one with opens == closes reads as open-for-zero-minutes rather
    than shut.

    `special` maps a day name to a short label for a day that is not open to
    walk-in/call-in booking on a fixed public schedule (e.g. "By concierge
    appointment only"). It is kept out of `days` on purpose: we were not given
    actual opening/closing times for it, and asserting an OpeningHoursSpecification
    with invented times would repeat the exact class of error this file exists
    to prevent. Special days are shown in prose and the footer, but never in
    the schema.org hours block.
    """

    def __init__(self, key, label, days, lunch=None, special=None):
        self.key = key
        self.label = label
        self.days = days
        self.lunch = lunch          # (start, end) or None
        self.special = special or {}  # day name -> label, excluded from schema

    @property
    def open_days(self):
        return [d for d in _ORDER if d in self.days]


JUPITER = Office(
    key="jupiter",
    label="Jupiter",
    days={
        "Monday": ("08:00", "17:00"),
        "Tuesday": ("08:00", "17:00"),
        "Wednesday": ("08:00", "17:00"),
        "Thursday": ("08:00", "17:00"),
        "Friday": ("08:00", "14:00"),
    },
    # Lunch closure removed 2026-08-24 at the owner's instruction: it was
    # rendering as a third line that mixed a Jupiter-only note with a
    # site-wide one ("Jupiter lunch closure 12:30-1:30 · Weekends closed"),
    # which read as one statement about both offices.
    #
    # Saturday is concierge-appointment-only here too (owner, 2026-08-24) --
    # the same arrangement as Palm Beach Gardens, and for the same reason it
    # lives in `special` rather than `days`: no fixed public hours were given,
    # so no OpeningHoursSpecification is asserted for it.
    special={"Saturday": "Concierge appointments only"},
)

# Updated 2026-08-21: open Mon/Tue/Wed 8-4:30 and Fri 8-2, closed Thursday
# and Sunday. Saturday is concierge-appointment-only -- no public walk-in/
# call-in hours were given for it, so it lives in `special`, not `days`; see
# the Office docstring for why that distinction is not just tidiness. No
# lunch closure was given -- so none is asserted. Do not "tidy" this by
# copying Jupiter's lunch break across; that guess is exactly the bug this
# file exists to prevent.
PALM_BEACH_GARDENS = Office(
    key="pbg",
    label="Palm Beach Gardens",
    days={
        "Monday": ("08:00", "16:30"),
        "Tuesday": ("08:00", "16:30"),
        "Wednesday": ("08:00", "16:30"),
        "Friday": ("08:00", "14:00"),
    },
    special={"Saturday": "Concierge appointments only"},
)

OFFICES = [JUPITER, PALM_BEACH_GARDENS]


# --------------------------------------------------------------------------
# Formatting helpers
# --------------------------------------------------------------------------

def _h12(hhmm):
    """"08:00" -> "8 AM"; "16:30" -> "4:30 PM". No ":00" on the hour."""
    h, m = (int(x) for x in hhmm.split(":"))
    suffix = "AM" if h < 12 else "PM"
    hour = h % 12 or 12
    return f"{hour}:{m:02d} {suffix}" if m else f"{hour} {suffix}"


def _runs(office):
    """Group consecutive open days that share the same hours.

    Mon-Thu 8-5 collapses to one run; Mon and Wed 8-4:30 stay two, because
    they are not adjacent. Rendering "Mon-Wed" for an office shut on Tuesday
    would be the same class of error as the schema bug.
    """
    runs = []
    for day in _ORDER:
        if day not in office.days:
            continue
        hours = office.days[day]
        idx = _ORDER.index(day)
        if runs and runs[-1][2] == hours and _ORDER.index(runs[-1][1]) == idx - 1:
            runs[-1][1] = day
        else:
            runs.append([day, day, hours])
    return runs


def _run_label(start, end, sep):
    if start == end:
        return _ABBR[start]
    return f"{_ABBR[start]}{sep}{_ABBR[end]}"


def line(office, ndash="&ndash;", amp="&amp;"):
    """One-line inline form, HTML-escaped by default.

    Jupiter -> "Mon&ndash;Thu 8 AM&ndash;5 PM &middot; Fri 8 AM&ndash;2 PM"
    PBG     -> "Mon &amp; Wed 8 AM&ndash;4:30 PM"
    """
    runs = _runs(office)
    # All open days share one set of hours and none are adjacent (PBG): read
    # better as "Mon & Wed 8-4:30" than as two separate clauses.
    if len(runs) > 1 and len({tuple(r[2]) for r in runs}) == 1:
        labels = [_run_label(s, e, ndash) for s, e, _ in runs]
        opens, closes = runs[0][2]
        joined = f" {amp} ".join(labels)
        return f"{joined} {_h12(opens)}{ndash}{_h12(closes)}"
    parts = []
    for start, end, (opens, closes) in runs:
        parts.append(f"{_run_label(start, end, ndash)} "
                     f"{_h12(opens)}{ndash}{_h12(closes)}")
    return " &middot; ".join(parts)


def plain(office):
    """Unescaped prose form, for llms.txt, assistant.js and the drift check."""
    return line(office, ndash="–", amp="&").replace("&middot;", "·")


def closed_note(office):
    """Human note about what is closed, HTML-escaped.

    Special days (see the Office docstring) are genuinely open on some basis,
    just not a fixed public schedule, so they are never folded into "Closed"
    -- they get their own clause appended instead.
    """
    shut = [d for d in _ORDER if d not in office.days and d not in office.special]
    weekend = {"Saturday", "Sunday"}
    bits = []
    if weekend.issubset(set(shut)):
        bits = [_ABBR[d] for d in shut if d not in weekend]
        bits.append("weekends")
    else:
        # Only bundle as "weekends" when both days are actually shut; a lone
        # closed Sunday (Saturday held out as special) must still be named,
        # not silently dropped the way a blanket weekend filter would.
        bits = [_ABBR[d] for d in shut]
    note = ""
    if bits:
        note = "Closed " + bits[0] if len(bits) == 1 else "Closed " + ", ".join(bits[:-1]) + " &amp; " + bits[-1]
    specials = " &middot; ".join(f"{_ABBR[d]}: {label}" for d, label in office.special.items() if d in _ORDER)
    if note and specials:
        return f"{note} &middot; {specials}"
    return note or specials


def ld(office, indent=6):
    """openingHoursSpecification array as JSON text, ready to paste into the
    hand-written JSON-LD blocks in template.html.

    Emitted as text rather than as a Python object because the schema blocks in
    template.html are literal JSON in the file, not built up programmatically.
    preflight.py json.loads() every block in the built output, so a malformed
    emission here fails the gate rather than shipping.
    """
    pad = " " * indent
    inner = pad + "  "
    entries = []
    for start, end, (opens, closes) in _runs(office):
        span = [d for d in _ORDER[_ORDER.index(start):_ORDER.index(end) + 1]]
        if len(span) == 1:
            day = f'"{span[0]}"'
        else:
            day = "[" + ", ".join(f'"{d}"' for d in span) + "]"
        entries.append(
            f'{inner}{{\n'
            f'{inner}  "@type": "OpeningHoursSpecification",\n'
            f'{inner}  "dayOfWeek": {day},\n'
            f'{inner}  "opens": "{opens}",\n'
            f'{inner}  "closes": "{closes}"\n'
            f'{inner}}}'
        )
    return "[\n" + ",\n".join(entries) + f"\n{pad}]"


def footer_rows(office):
    """The <li> rows for one office, in the footer's two-span layout.

    Matches the existing .footer-hours CSS: each li is a flex row with the day
    label left and the hours right. Closed days are stated explicitly rather
    than omitted -- "Tue, Thu, Fri  Closed" is the single most useful line on
    the Gardens listing, and leaving it out is what let people assume the
    Jupiter schedule applied to both.
    """
    rows = []
    for start, end, (opens, closes) in _runs(office):
        rows.append(f'<li><span>{_run_label(start, end, "&ndash;")}</span> '
                    f'<span>{_h12(opens)} &ndash; {_h12(closes)}</span></li>')
    shut = [d for d in _ORDER if d not in office.days and d not in office.special]
    if shut:
        weekend = {"Saturday", "Sunday"}
        if weekend.issubset(set(shut)):
            weekdays = [_ABBR[d] for d in shut if d not in weekend]
            if weekdays:
                rows.append(f'<li><span>{", ".join(weekdays)}</span> '
                            f'<span>Closed</span></li>')
            rows.append('<li><span>Sat&ndash;Sun</span> <span>Closed</span></li>')
        else:
            # A lone closed weekend day (the other held out as `special`)
            # must still get its own row rather than being filtered away.
            rows.append(f'<li><span>{", ".join(_ABBR[d] for d in shut)}</span> '
                        f'<span>Closed</span></li>')
    for day, label in office.special.items():
        rows.append(f'<li><span>{_ABBR[day]}</span> <span>{label}</span></li>')
    return rows


def footer_html():
    """The footer Office Hours block: both offices, each labelled.

    Labelling is the point. The footer previously showed one unlabelled set of
    hours on every page of a two-office site, which reads as "the practice is
    open these hours" and is false for the Gardens office five days a week.
    """
    out = []
    for office in OFFICES:
        out.append(f'<li class="footer-hours-office"><span>{office.label}</span></li>')
        out.extend(footer_rows(office))
    return "\n            ".join(out)
